exec uwsm finalize sway

exec swayidle -w \
	timeout 300 '/run/wrappers/bin/wlock -a 3b4252 -i 2e3440 -c 000000 -f bf616a' \
	timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
	before-sleep '/run/wrappers/bin/wlock -a 3b4252 -i 2e3440 -c 000000 -f bf616a'

exec $uwsmify ~/dotfiles/scripts/workspace-renamer.py
exec $uwsmify ~/dotfiles/scripts/rofi-polkit