input type:touchpad {
	dwt enabled
	tap enabled
	drag_lock disabled
	natural_scroll enabled
	middle_emulation enabled
}

input 1133:16500:Logitech_G304 {
	natural_scroll disabled
	dwt false
	accel_profile "flat"
	pointer_accel 0
}

input type:keyboard {
	xkb_layout "us"
}
