assign [app_id="^app.zen_browser.zen$"] workspace number 1
assign [app_id="^equibop$"] workspace number 2
assign [app_id="^com.rtosta.zapzap$"] workspace number 2
assign [app_id="^code-insiders$"] workspace number 3

for_window [app_id="^equibop$"] layout tabbed
for_window [app_id="^com.rtosta.zapzap$"] layout tabbed