font pango:NotoSansM Nerd Font 10
output * bg $nord0 solid_color

# class                 border   bground  text     indicator child_border
client.focused          $nord10  $nord10  $nord6   $nord9    $nord10
client.focused_inactive $nord3   $nord3   $nord6   $nord1    $nord3
client.unfocused        $nord1   $nord1   $nord6   $nord1    $nord1
client.urgent           $nord12  $nord12  $nord6   $nord12   $nord12
client.placeholder      $nord3   $nord0   $nord6   $nord3    $nord3
client.background       $nord0


default_border normal 2
default_floating_border normal 2

titlebar_padding 2
titlebar_border_thickness 0

gaps inner 2px
gaps outer 0px

seat * xcursor_theme Adwaita 24