#! /bin/sh
# This is a modified version of https://github.com/czaplicki/rofi-polkit-agent/
# adapted to use tofi instead of rofi.

case "$*" in 'h'|'help'|'-h'|'-help'|'--help')
    echo 'Usage: rofi-polkit-agent [ROFI_OPTIONS]...
Polkit agent using rofi for GUI.

Start the polkit agent, with default options :
  rofi-polkit-agent

Start the polkit agent, with any additional argument passed directly to rofi :
  rofi-polkit-agent -theme PATH -monitor NUM
'
esac

if test "$1" != '_CALLED_INTERNALLY'; then
    prepParams() { for i in "$@"; do printf "'%s' " "$i"; done }
    parameters="$(prepParams "$@")"

    cmd-polkit-agent -s -c "$0 _CALLED_INTERNALLY $parameters*"
else
    shift 1

    while read -r msg; do
        if echo "$msg" | jq -e '.action == "request password"' 1>/dev/null 2>/dev/null
        then
            message="$(printf '%s' "$msg" | jq -rc '.message // "Authentication required"')"

            full_prompt="${message}"

            response="$(printf '' | tofi \
                --prompt-text "${full_prompt} " \
                 -c ~/dotfiles/modules/tofi/configs/polkit)"

            if test -z "$response"
            then echo '{"action":"cancel"}'
            else echo "{\"action\":\"authenticate\",\"password\": \"$response\"}"
            fi
        fi
    done
fi
