exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec systemctl --user stop graphical-session.target
exec systemctl --user start sway-session.target
exec exec systemctl --user daemon-reload
exec systemctl --user start nixos-autostart.target


# clean up cava when sway is reset
exec_always pkill -9 -f cava && pkill -9 -f cava-waybar

exec swayidle -w \
	timeout 300 '/run/wrappers/bin/wlock -a 524f67 -i 403d52 -c 000000 -f eb6f92' \
	timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
	before-sleep '/run/wrappers/bin/wlock -a 524f67 -i 403d52 -c 000000 -f eb6f92'

exec ~/dotfiles/scripts/workspace-renamer.py
exec ~/dotfiles/scripts/rofi-polkit

exec foot --server
exec mako

exec systemd-inhibit --who="sway" --why="user" --what=handle-power-key --mode=block sleep infinity


exec flatpak run dev.vencord.Vesktop
exec flatpak run com.rtosta.zapzap